//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZOper.TechTester.WebServiceWebSI.App_WebReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="App_WebReferences.HelloWorldSoap")]
    public interface HelloWorldSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SayResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Say", ReplyAction="*")]
        EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse Say(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Say", ReplyAction="*")]
        System.Threading.Tasks.Task<EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse> SayAsync(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        double addition(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        System.Threading.Tasks.Task<double> additionAsync(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        double subtract(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<double> subtractAsync(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplication", ReplyAction="*")]
        double multiplication(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<double> multiplicationAsync(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        double division(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        System.Threading.Tasks.Task<double> divisionAsync(double i, double j);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Say", Namespace="http://tempuri.org/", Order=0)]
        public EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequestBody Body;
        
        public SayRequest() {
        }
        
        public SayRequest(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SayRequestBody {
        
        public SayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayResponse", Namespace="http://tempuri.org/", Order=0)]
        public EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponseBody Body;
        
        public SayResponse() {
        }
        
        public SayResponse(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayResult;
        
        public SayResponseBody() {
        }
        
        public SayResponseBody(string SayResult) {
            this.SayResult = SayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldSoapChannel : EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldSoapClient : System.ServiceModel.ClientBase<EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap>, EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap {
        
        public HelloWorldSoapClient() {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap.Say(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest request) {
            return base.Channel.Say(request);
        }
        
        public string Say() {
            EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest inValue = new EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest();
            inValue.Body = new EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequestBody();
            EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse retVal = ((EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap)(this)).Say(inValue);
            return retVal.Body.SayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse> EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap.SayAsync(EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest request) {
            return base.Channel.SayAsync(request);
        }
        
        public System.Threading.Tasks.Task<EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayResponse> SayAsync() {
            EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest inValue = new EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequest();
            inValue.Body = new EZOper.TechTester.WebServiceWebSI.App_WebReferences.SayRequestBody();
            return ((EZOper.TechTester.WebServiceWebSI.App_WebReferences.HelloWorldSoap)(this)).SayAsync(inValue);
        }
        
        public double addition(double i, double j) {
            return base.Channel.addition(i, j);
        }
        
        public System.Threading.Tasks.Task<double> additionAsync(double i, double j) {
            return base.Channel.additionAsync(i, j);
        }
        
        public double subtract(double i, double j) {
            return base.Channel.subtract(i, j);
        }
        
        public System.Threading.Tasks.Task<double> subtractAsync(double i, double j) {
            return base.Channel.subtractAsync(i, j);
        }
        
        public double multiplication(double i, double j) {
            return base.Channel.multiplication(i, j);
        }
        
        public System.Threading.Tasks.Task<double> multiplicationAsync(double i, double j) {
            return base.Channel.multiplicationAsync(i, j);
        }
        
        public double division(double i, double j) {
            return base.Channel.division(i, j);
        }
        
        public System.Threading.Tasks.Task<double> divisionAsync(double i, double j) {
            return base.Channel.divisionAsync(i, j);
        }
    }
}
