#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EZOper.TechTester.CnaSptAppSI.Resource", IsApplication=true)]

namespace EZOper.TechTester.CnaSptAppSI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int ab_background = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ab_bottom_shadow_1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ab_bottom_shadow_2 = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int action_bar_title_color = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int main_background = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int xam_blue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int xam_dark_blue = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int xam_gray = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int xam_green = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int xam_light_gray = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int xam_purple = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_addbtn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int TTTSwipeToRefresh_AbBg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int TTTSwipeToRefresh_DiscreteShadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int TTTSwipeToRefresh_Logo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int AuthorName = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int DownloadedImageView = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int GetButton = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int LvwAreaNameList = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int LvwFunctionList = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int PostAvatar = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int PostText = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int PostTime = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int PostTimeSecondary = 2131165207;
			
			// aapt resource value: 0x7f070010
			public const int PostTitle = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int ResultEditText = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int ResultTextView = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int clickButton = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int container = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int downloadButton = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int imageView1 = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout2 = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int progressBar = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int refresher = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int relativeLayout1 = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TTTAsyncAwaitLoad_Img = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TTTAsyncAwaitLoad_ImgAndNoted = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TTTAsyncImageAndroid_Download = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TTTMainListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TTTSwipeToRefresh_Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TTTSwipeToRefresh_PostItem = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int GoAndGet = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int XamActionBarStyle = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int XamActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int XamActionBarTitleStyle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
